### PR TITLE
php7 fixes - fix constructors and 2 common notices

### PR DESCRIPTION
**Pull request by SjonHortensius**
I've fixed all old-style constructors and 2 notices I saw frequently (in `classes/Misc.php`). This change is backwards compatible with PHP_VERSION > PHP4 (which I hope no-one still runs)

### CODE REVIEW

**Comment by Skatox** [comment]
My installation also complains due to this, this is an important commit

**Comment by youssefbenhssaien** [comment]
This is an important pull request !
@SjonHortensius  can you please update your pull request ?

**Comment by denaje** [comment]
@SjonHortensius and all, I merged this PR into https://github.com/myfarms/phppgadmin. Other PRs welcome.

**Comment by SjonHortensius** [comment]
@xzilla would you clarify why you ignored this and other pull requests and choose to do the same work yourself 3 years later (in 1ea83accae6229e6b63844d948ed144fe486fee0)?

I'd be happy to contribute other fixes - but it'd be nice if they'd actually be used :)

**Comment by xzilla** [comment]
@SjonHortensius I'm not sure there is a succinct way to summarize the state of development the last few years, but most of it was related to timing, a plethora of PRs all re-implementing the same thing (yours was not the first, how do you pick just one?), and many of the PR's conflating multiple issues into a single PR (class updates vs fixing warnings vs pgsql supported versions). Right now I'm slowly working through some of the backlog of PRs to clean up the repo, and have some changes to the DEVELOPERS file to help improve workflow (more clearly outlining feature branches). I do hope you'll consider contributing in the future. If you want to discuss more, you can find me on the postgres slack team.

**Comment by SjonHortensius** [comment]
@xzilla that's actually very sensible - especially the part about not implementing multiple fixes in a single PR. You could consider looking at [CONTRIBUTING](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) to emphasize this. Also - if you'd have replied with that suggestion to any of the PRs I'm pretty sure people would have accommodated (I know I would have).

Thanks for the explanation - I'll be sure to send more PRs your way. Please consider closing other duped PRs (eg #16, #21) as well

**Pull request closed without merging**
