### PR TITLE
Support postgresql 10.0

### PR DESCRIPTION
**Pull request by scottdriscoll**
Fixes: `Version of PostgreSQL not supported. Please upgrade to version or later.`

### CODE REVIEW

**Comment by rdmendo** [comment]
+1 plz

**Comment by marcosbc** [comment]
This is an alternative patch for doing the same, but with support for PostgreSQL 10 and superior versions:

```--- classes/database/Connection.php	2013-04-15 00:59:58.000000000 +0200
+++ /home/bitnami/Connection.php	2017-11-03 10:51:01.436902230 +0100
@@ -91,7 +91,8 @@
 		/* All <7.4 versions are not supported */
 		// if major version is 7 or less and wasn't cought in the
 		// switch/case block, we have an unsupported version.
-		if ((int)substr($version, 0, 1) < 8)
+		$versionArray = explode('.', $version);
+		if ($versionArray[0] < 8)
 			return null;

 		// If unknown version, then default to latest driver```

**Comment by septianopqr** [comment]
@scottdriscoll Can you add `10.1` version ?

**Comment by scottdriscoll** [comment]
Updated to better support future versions of pg10, as well as correctly point the help docs to the correct online location.

Since postgres changed their versioning scheme, the "major.minor.patch" system has been deprecated. It is now "major.patch", so this PR should work until Postgresql 11 is released.

**Comment by SalahAdDin** [comment]
@nikolayv81 Please, we need it!

**Comment by denaje** [comment]
@scottdriscoll and all, I merged this PR into https://github.com/myfarms/phppgadmin. Other PRs welcome.

**Comment by SalahAdDin** [comment]
@denaje, thank you, how can i update it in my computer?

**Comment by denaje** [comment]
Hi, my fork isn't available in any OS repositories, but you could clone the
repo on your machine and point your web server to it like you would for a
normal install.

**Comment by xzilla** [comment]
Similar functionality has been merged upstream (https://github.com/phppgadmin/phppgadmin/). Thanks for your submission/efforts. Closing this PR.

**Pull request closed without merging**
